generatorName: ruby
typeMappings: {}
additionalProperties:
  gemAuthor: HelloSign
  gemAuthorEmail: apisupport@hellosign.com
  gemDescription: Official HelloSign APIv3 OpenAPI Ruby SDK
  gemHomepage: https://hellosign.com
  gemLicense: MIT
  gemName: hello_sign
  gemRequiredRubyVersion: '>= 2.7'
  moduleName: HelloSign
  sortModelPropertiesByRequiredFlag: true
  legacyDiscriminatorBehavior: true
files:
  event_callback_helper.mustache:
    templateType: SupportingFiles
    destinationFilename: lib/hello_sign/event_callback_helper.rb
globalProperties:
  apiTests: false
  modelTests: false
