generatorName: ruby
typeMappings: {}
additionalProperties:
  gemAuthor: HelloSign
  gemAuthorEmail: apisupport@hellosign.com
  gemDescription: Official HelloSign APIv3 OpenAPI Ruby SDK
  gemHomepage: https://hellosign.com
  gemLicense: MIT
  gemName: hellosign-ruby-sdk
  gemRequiredRubyVersion: '>= 2.7'
  moduleName: HelloSign
  gemVersion: 6.0.0-beta22.24
  sortModelPropertiesByRequiredFlag: true
  legacyDiscriminatorBehavior: true
files:
  event_callback_helper.mustache:
    templateType: SupportingFiles
    destinationFilename: lib/hellosign-ruby-sdk/event_callback_helper.rb
globalProperties:
  apiTests: false
  modelTests: false
